---
services:
  clickhouse1:
    image: "clickhouse:latest"
    user: &user "${UID:?You must do 'export UID' to launch}:${GID}"
    restart: always
    environment:
      HOME: /tmp
      SHARD_ID: 1
      REPLICA_ID: 1
    depends_on:
      - zoo1
    volumes:
      - ./data/clickhouse1/:/var/lib/clickhouse/
      - ./data/clickhouse1/:/var/log/clickhouse-server/
      - ./configs/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml:ro
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    cap_add: &caps
      - SYS_PTRACE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_NICE
    networks:
      - keeper-cluster
  clickhouse2:
    image: "clickhouse:latest"
    user: *user
    restart: always
    environment:
      HOME: /tmp
      SHARD_ID: 1
      REPLICA_ID: 2
    depends_on:
      - zoo1
    volumes:
      - ./data/clickhouse2/:/var/lib/clickhouse/
      - ./data/clickhouse2/:/var/log/clickhouse-server/
      - ./configs/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml:ro
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    cap_add: *caps
    networks:
      - keeper-cluster
  zoo1:
    image: "clickhouse:latest"
    restart: always
    user: *user
    environment:
      HOME: /tmp
      KEEPER_ID: 1
    volumes:
      - ./data/zoo1:/var/lib/clickhouse-keeper
      - ./data/zoo1:/var/lib/clickhouse
      - ./data/zoo1:/var/log/clickhouse-keeper
      - ./configs/keeper_single.xml:/etc/clickhouse-keeper/keeper_config.xml:ro
      - ./configs/logger.xml:/etc/clickhouse-keeper/keeper_config.d/logger.xml:ro
    cap_add: *caps
    command: &keeper-cmd |
      clickhouse-keeper --config-file /etc/clickhouse-keeper/keeper_config.xml
    networks:
      - keeper-cluster
  zoo2:
    image: "clickhouse:latest"
    profiles:
      - keeper-extend
      - keeper-cluster
    restart: always
    user: *user
    environment:
      HOME: /tmp
      KEEPER_ID: 2
    volumes:
      - ./data/zoo2:/var/lib/clickhouse-keeper
      - ./data/zoo2:/var/lib/clickhouse
      - ./data/zoo2:/var/log/clickhouse-keeper
      - ./configs/keeper_cluster.xml:/etc/clickhouse-keeper/keeper_config.xml:ro
      - ./configs/logger.xml:/etc/clickhouse-keeper/keeper_config.d/logger.xml:ro
    cap_add: *caps
    command: *keeper-cmd
    networks:
      - keeper-cluster
  zoo3:
    image: "clickhouse:latest"
    profiles:
      - keeper-cluster
    restart: always
    user: *user
    environment:
      HOME: /tmp
      KEEPER_ID: 3
    volumes:
      - ./data/zoo3:/var/lib/clickhouse-keeper
      - ./data/zoo3:/var/lib/clickhouse
      - ./data/zoo3:/var/log/clickhouse-keeper
      - ./configs/keeper_cluster.xml:/etc/clickhouse-keeper/keeper_config.xml:ro
      - ./configs/logger.xml:/etc/clickhouse-keeper/keeper_config.d/logger.xml:ro
    cap_add: *caps
    command: *keeper-cmd
    networks:
      - keeper-cluster

networks:
  keeper-cluster:
