---
services:
  clickhouse:
    image: "clickhouse/clickhouse-server:latest"
    user: &user "${UID:?You must do 'export UID' to launch}:65535"
    restart: always
    environment:
      HOME: /tmp
    depends_on:
      - zoo1
    volumes:
      - ./data/clickhouse/:/var/lib/clickhouse/
      - ./data/clickhouse/:/var/log/clickhouse-server/
      - ./configs/zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml:ro
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    cap_add: &caps
      - SYS_PTRACE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_NICE
    networks:
      - keeper-cluster
  zoo1:
    image: "clickhouse/clickhouse-keeper:latest"
    restart: always
    user: *user
    environment:
      HOME: /tmp
      KEEPER_ID: 1
    volumes:
      - ./data/zoo1:/var/lib/clickhouse-keeper
      - ./data/zoo1:/var/lib/clickhouse
      - ./data/zoo1:/var/log/clickhouse-keeper
      - ./configs/keeper_single.xml:/etc/clickhouse-keeper/keeper_config.xml:ro
    cap_add: *caps
    networks:
      - keeper-cluster
  zoo2:
    image: "clickhouse/clickhouse-keeper:latest"
    profiles:
      - keeper-extend
      - keeper-cluster
    restart: always
    user: *user
    environment:
      HOME: /tmp
      KEEPER_ID: 2
    volumes:
      - ./data/zoo2:/var/lib/clickhouse-keeper
      - ./data/zoo2:/var/lib/clickhouse
      - ./data/zoo2:/var/log/clickhouse-keeper
      - ./configs/keeper_cluster.xml:/etc/clickhouse-keeper/keeper_config.xml:ro
    cap_add: *caps
    networks:
      - keeper-cluster
  zoo3:
    image: "clickhouse/clickhouse-keeper:latest"
    profiles:
      - keeper-cluster
    restart: always
    user: *user
    environment:
      HOME: /tmp
      KEEPER_ID: 3
    volumes:
      - ./data/zoo3:/var/lib/clickhouse-keeper
      - ./data/zoo3:/var/lib/clickhouse
      - ./data/zoo3:/var/log/clickhouse-keeper
      - ./configs/keeper_cluster.xml:/etc/clickhouse-keeper/keeper_config.xml:ro
    cap_add: *caps
    networks:
      - keeper-cluster

networks:
  keeper-cluster:
